kind: Service
apiVersion: v1
metadata:
  name: pibgama-backoffice
  labels:
    run: pibgama-backoffice
spec:
  selector:
    app: pibgama-backoffice
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
