name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create env to production
      run: |
        cat .env | sed s/VUE_APP_HOST_VALUE/'${{ secrets.VUE_APP_HOST }}'/ >> .env.production
        docker login docker.pkg.github.com -u joaopaulogse -p ${{ secrets.DOCKER_GITHUB_TOKEN }}
        docker build -t docker.pkg.github.com/joaopaulogse/pibgama-backoffice/pibgama-backoffice:latest .
        docker push docker.pkg.github.com/joaopaulogse/pibgama-backoffice/pibgama-backoffice:latest
